//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAClassifieds.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TAC_User
    {
        public System.Guid UserId { get; set; }

        [Required]
        [Display(Name = "Email*")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password*")]
        public string UPassword { get; set; }

        [Required]
        [Display(Name = "First Name*")]
        public string First_Name { get; set; }

        [Required]
        [Display(Name = "Last Name*")]
        public string Last_Name { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }


        [Display(Name = "Address")]
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Country { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        public virtual TAC_Country TAC_Country { get; set; }
        public virtual TAC_Country TAC_Country1 { get; set; }

        //[Required]
        [DataType(DataType.Password)]
        [Display(Name = "Repeat Password*")]
        public string RepeatPassword { get; set; }

        [Required]
        [Display(Name = "Terms and Conditions")]
        public bool TermsAndConditions { get; set; }

        [Display(Name = "Error Message")]
        public string ErrorMessage { get; set; }

    }
}
