//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAClassifieds.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TAC_ClassifiedContact
    {
        public int ContactId { get; set; }

        [Required]
        [Display(Name = "Contact Name*")]
        public string ContactName { get; set; }

        [Required]
        [RegularExpression(@"^((\+\d{1,3}[- ]?)?\d{10})$",ErrorMessage = "Please enter a valid mobile number.")]
        [Display(Name = "Contact Phone No.*")]
        public string ContactPhone { get; set; }

        [Required]
        [Display(Name = "Contact City*")]
        public string ContactCity { get; set; }
        public int ClassifiedId { get; set; }
    
        public virtual TAC_Classified TAC_Classified { get; set; }
    }
}
