//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAClassifieds.Models.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TAC_ClassifiedContact
    {
        public int ContactId { get; set; }
        [Required]
        [DisplayName("Name*")]
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        [Required]
        [DisplayName("City*")]
        public string ContactCity { get; set; }
        public int ClassifiedId { get; set; }
    
        public virtual TAC_Classified TAC_Classified { get; set; }
    }
}
